### ISSUE TITLE
Visualization does not seem to work properly (view -> series) 

### ISSUE THREAD

**Issue by JoaoPeriquito** [QIB-Sheffield/wezel#2]
I am able to visualize images using the option view -> draw ROI. However I am unable to visualize images using view -> series (something seems to appear in the histogram)

![Weasel_error](https://user-images.githubusercontent.com/48806417/172592458-a316d981-7475-43a1-bd91-62f0d7732065.PNG)

**Comment by plaresmedima** [comment]
This should be fixed now @JoaoPeriquito - please check when you get a chance..

**Comment by plaresmedima** [comment]
This issue came in with mater versions of pyqtgraph. Reverted to older versions in requirements.
