### ISSUE TITLE
demo.py import error when using python 3.6.6

### ISSUE THREAD

**Issue by KanishkaS** [QIB-Sheffield/wezel#3]
Python script in folder weasel->actions->demo.py throws import error when using python 3.6.6 (global setting) in VScode. 

Replaced lines below in demo.py (in iBEAt project only):
import weasel.actions as actions

 actions.about.menu(parent.menu('About'))    
 actions.folder.menu(parent.menu('File'))
 actions.edit.menu(parent.menu('Edit'))

  view.action(actions.view.Image, text='Display image')
  view.action(actions.view.Series, text='Display series')
  view.action(actions.view.Region, text='Draw region')
  
  view.action(actions.view.CloseWindows, text='Close windows')
  view.action(actions.view.TileWindows, text='Tile windows')

to the following:
from weasel.actions.about import menu as aboutmenu
from weasel.actions.folder import menu as foldermenu
from weasel.actions.edit import menu as editmenu
from weasel.actions.view import Image
from weasel.actions.view import Series
from weasel.actions.view import Region
from weasel.actions.view import CloseWindows
from weasel.actions.view import TileWindows

    aboutmenu(parent.menu('About'))
    foldermenu(parent.menu('File'))
    editmenu(parent.menu('Edit'))
   
    view.action(Image, text='Display image')
    view.action(Series, text='Display series')
    view.action(Region, text='Draw region')
   
    view.action(CloseWindows, text='Close windows')
    view.action(TileWindows, text='Tile windows')

**Comment by plaresmedima** [comment]
This should be fixed now - @KanishkaS can you check using pip install wezel?

**Comment by KanishkaS** [comment]
new error with pip install wezel below:

PS C:\Users\medkshaa\Documents\GitHub> & C:/Users/medkshaa/AppData/Local/Programs/Python/Python36/python.exe c:/Users/medkshaa/Documents/GitHub/wezel/dev/dev.py
Traceback (most recent call last):
  File "c:/Users/medkshaa/Documents/GitHub/wezel/dev/dev.py", line 10, in <module>
    import wezel
  File "C:\Users\medkshaa\AppData\Local\Programs\Python\Python36\lib\site-packages\wezel\__init__.py", line 1, in <module>
    from wezel.core import *
  File "C:\Users\medkshaa\AppData\Local\Programs\Python\Python36\lib\site-packages\wezel\core.py", line 8, in <module>
    import wezel.widgets as widgets
  File "C:\Users\medkshaa\AppData\Local\Programs\Python\Python36\lib\site-packages\wezel\widgets\__init__.py", line 7, in <module>
    from .array_view import *
  File "C:\Users\medkshaa\AppData\Local\Programs\Python\Python36\lib\site-packages\wezel\widgets\array_view.py", line 12, in <module>
    from dbdicom.classes.image import QImage
ImportError: cannot import name 'QImage'

**Comment by plaresmedima** [comment]
Thanks Kanishka - please include some more info with a bug report - not
juse the error but also the code snippet generating it.

Are you using a virtual environment? dev.py is not part of the pip install
package I think. Maybe iy have the source code locallt as well?
